/**
* @file route.h
* @brief Simulated generated routing contract for the example platform.
*
* The LDP DDS runtime consumes this file as the generated boundary between the
* ECOA model and DDS transport.  Internal main/PD control routes are generated
* separately from user business wire routes.
*/

#ifndef _EXAMPLE_ROUTE_H
#define _EXAMPLE_ROUTE_H

#include <stddef.h>

#include "ldp_dds_route.h"

#define ID_INITIALIZE_event "INITIALIZE"
#define ID_START_event "START"
#define ID_STOP_event "STOP"

/* Legacy local connection identifiers. In DDS mode these are compatibility
 * interface ids for the current generated routers, not real DDS addresses. */
#define MAIN_SENDER_PORT 41001
#define MAIN_RECEIVER_PORT 41002
#define SENDER_CONTROL_PORT 46001
#define RECEIVER_CONTROL_PORT 46002
#define RECEIVER_DATA_PORT 30002

#define MAIN_SENDER_ADDR "127.0.0.1"
#define MAIN_RECEIVER_ADDR "127.0.0.1"
#define SENDER_CONTROL_ADDR "127.0.0.1"
#define RECEIVER_CONTROL_ADDR "127.0.0.1"
#define RECEIVER_DATA_ADDR "127.0.0.1"

/* Example operation ids. A real generated route.h would keep the existing
 * module and wire operation ids here. */
#define OP_DATA 42
#define OP_ACK 43

/* The LDP DDS runtime uses one internal communication domain. */
#define LDP_DDS_DOMAIN_ID 0
#define LDP_DDS_PROJECT_NAME "example"
#define LDP_DDS_DEFAULT_PARTITION "platform.example"

/* Internal LDP control topic.  This is generated by LDP and should not need
 * per-PD user configuration. */
#define LDP_DDS_CONTROL_TOPIC "ECOA_example_platform_control"

/* Business topics.  The default topics are deterministic wire-derived names;
 * the effective topic may be user-overridden.  This example deliberately maps
 * both business wires to one semantic topic to exercise shared-topic routing. */
#define LDP_DDS_TOPIC_DEFAULT_SENDER_TO_RECEIVER_DATA "ECOA_example_sender_receiver_data"
#define LDP_DDS_TOPIC_DEFAULT_RECEIVER_TO_SENDER_ACK "ECOA_example_receiver_sender_ack"
#define LDP_DDS_TOPIC_MISSION_SENDER_RECEIVER "Mission_Sender_Receiver"

/* Logical ECOA identities. */
#define LDP_DDS_PLATFORM_EXAMPLE 1
#define LDP_DDS_NODE_LOCAL 1
#define LDP_DDS_PD_MAIN 1
#define LDP_DDS_PD_SENDER 2
#define LDP_DDS_PD_RECEIVER 3

#define LDP_DDS_IFACE_MAIN_TO_SENDER 1001
#define LDP_DDS_IFACE_MAIN_TO_RECEIVER 1002
#define LDP_DDS_IFACE_SENDER_TO_MAIN 1003
#define LDP_DDS_IFACE_RECEIVER_TO_MAIN 1004
#define LDP_DDS_IFACE_SENDER_TO_RECEIVER 1005
#define LDP_DDS_IFACE_RECEIVER_TO_SENDER 1006

#define LDP_DDS_WIRE_SENDER_TO_RECEIVER_DATA 2001
#define LDP_DDS_WIRE_RECEIVER_TO_SENDER_ACK 2002

#define LDP_DDS_ENTITY_ROUTE_COUNT 4
static const ldp_dds_entity_route LDP_DDS_ENTITY_ROUTES[LDP_DDS_ENTITY_ROUTE_COUNT] = {
	{
		LDP_DDS_PLATFORM_EXAMPLE,
		LDP_DDS_ENTITY_PLATFORM,
		"example_platform",
		"example_platform",
		NULL,
		NULL,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_DEFAULT_PARTITION
	},
	{
		LDP_DDS_PD_MAIN,
		LDP_DDS_ENTITY_MAIN,
		"main",
		"example_platform",
		"local_node",
		"main",
		LDP_DDS_DOMAIN_ID,
		"pd.main"
	},
	{
		LDP_DDS_PD_SENDER,
		LDP_DDS_ENTITY_PD,
		"PD_sender_PD",
		"example_platform",
		"local_node",
		"PD_sender_PD",
		LDP_DDS_DOMAIN_ID,
		"pd.sender"
	},
	{
		LDP_DDS_PD_RECEIVER,
		LDP_DDS_ENTITY_PD,
		"PD_receiver_PD",
		"example_platform",
		"local_node",
		"PD_receiver_PD",
		LDP_DDS_DOMAIN_ID,
		"pd.receiver"
	}
};

#define LDP_DDS_CONTROL_ROUTE_COUNT 4
static const ldp_dds_control_route LDP_DDS_CONTROL_ROUTES[LDP_DDS_CONTROL_ROUTE_COUNT] = {
	{
		LDP_DDS_IFACE_MAIN_TO_SENDER,
		"main_to_sender_control",
		LDP_DDS_PD_MAIN,
		LDP_DDS_PD_SENDER,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_CONTROL_TOPIC,
		"pd.sender",
		MAIN_SENDER_PORT,
		SENDER_CONTROL_PORT
	},
	{
		LDP_DDS_IFACE_MAIN_TO_RECEIVER,
		"main_to_receiver_control",
		LDP_DDS_PD_MAIN,
		LDP_DDS_PD_RECEIVER,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_CONTROL_TOPIC,
		"pd.receiver",
		MAIN_RECEIVER_PORT,
		RECEIVER_CONTROL_PORT
	},
	{
		LDP_DDS_IFACE_SENDER_TO_MAIN,
		"sender_to_main_control",
		LDP_DDS_PD_SENDER,
		LDP_DDS_PD_MAIN,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_CONTROL_TOPIC,
		"pd.main",
		SENDER_CONTROL_PORT,
		MAIN_SENDER_PORT
	},
	{
		LDP_DDS_IFACE_RECEIVER_TO_MAIN,
		"receiver_to_main_control",
		LDP_DDS_PD_RECEIVER,
		LDP_DDS_PD_MAIN,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_CONTROL_TOPIC,
		"pd.main",
		RECEIVER_CONTROL_PORT,
		MAIN_RECEIVER_PORT
	}
};

#define LDP_DDS_WIRE_ROUTE_COUNT 2
static const ldp_dds_wire_route LDP_DDS_WIRE_ROUTES[LDP_DDS_WIRE_ROUTE_COUNT] = {
	{
		LDP_DDS_WIRE_SENDER_TO_RECEIVER_DATA,
		"sender/data__receiver/input",
		"sender",
		"data",
		"receiver",
		"input",
		LDP_DDS_PD_SENDER,
		LDP_DDS_PD_RECEIVER,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_TOPIC_DEFAULT_SENDER_TO_RECEIVER_DATA,
		LDP_DDS_TOPIC_MISSION_SENDER_RECEIVER,
		LDP_DDS_TOPIC_SOURCE_USER,
		LDP_DDS_DEFAULT_PARTITION,
		LDP_DDS_IFACE_SENDER_TO_RECEIVER,
		RECEIVER_DATA_PORT
	},
	{
		LDP_DDS_WIRE_RECEIVER_TO_SENDER_ACK,
		"receiver/ack__sender/control",
		"receiver",
		"ack",
		"sender",
		"control",
		LDP_DDS_PD_RECEIVER,
		LDP_DDS_PD_SENDER,
		LDP_DDS_DOMAIN_ID,
		LDP_DDS_TOPIC_DEFAULT_RECEIVER_TO_SENDER_ACK,
		LDP_DDS_TOPIC_MISSION_SENDER_RECEIVER,
		LDP_DDS_TOPIC_SOURCE_USER,
		LDP_DDS_DEFAULT_PARTITION,
		LDP_DDS_IFACE_RECEIVER_TO_SENDER,
		SENDER_CONTROL_PORT
	}
};

#define LDP_DDS_OPERATION_ROUTE_COUNT 2
static const ldp_dds_operation_route LDP_DDS_OPERATION_ROUTES[LDP_DDS_OPERATION_ROUTE_COUNT] = {
	{
		OP_DATA,
		1,
		2,
		LDP_DDS_IFACE_SENDER_TO_RECEIVER,
		LDP_DDS_IFACE_RECEIVER_TO_SENDER
	},
	{
		OP_ACK,
		2,
		1,
		LDP_DDS_IFACE_RECEIVER_TO_SENDER,
		LDP_DDS_IFACE_SENDER_TO_RECEIVER
	}
};

#endif /* _EXAMPLE_ROUTE_H */
