set(APR_ROOT_PATH ${APR_DIR} CACHE STRING "APR install path")
set(log4cplus_ROOT_PATH ${LOG4CPLUS_DIR} CACHE PATH "log4cplus install dir")
set(CUNIT_ROOT_PATH ${CUNIT_DIR} CACHE PATH "CUnit install dir")
# set(ZLOG_ROOT_PATH ${ZLOG_DIR} CACHE PATH "zlog install dir")

set(LDP_LOG_USE "console" CACHE STRING "Use log4cplus, zlog or console for logging")
set(LDP_LINK_TYPE STATIC CACHE STRING "Use STATIC or SHARED link type")
set(CMAKE_BUILD_TYPE Debug CACHE STRING "build type")
set(USER_CMAKE_C_FLAGS "-Wall -std=c99" CACHE STRING "user compilation flag")
set(USER_CMAKE_CXX_FLAGS "-Wall -std=gnu++11" CACHE STRING "user compilation flag")
set(CMAKE_USE_AF_UNIX false CACHE BOOL "AF_INET or AF_UNIX socket family")
set(USE_APEX_API ON CACHE BOOL "Use the APEX APR compatibility shim")

# Select exactly one local transport here: TCP, UDP, DDS or APEX.
set(LDP_LOCAL_TRANSPORT TCP CACHE STRING "Local transport backend")
set_property(CACHE LDP_LOCAL_TRANSPORT PROPERTY STRINGS TCP UDP DDS APEX)

string(TOUPPER "${LDP_LOCAL_TRANSPORT}" LDP_LOCAL_TRANSPORT)
if(LDP_LOCAL_TRANSPORT STREQUAL "DDS")
	set(CMAKE_USE_DDS_PROTO true CACHE BOOL "DDS protocol" FORCE)
	set(CMAKE_USE_UDP_PROTO false CACHE BOOL "UDP protocol" FORCE)
	set(CMAKE_USE_APEX_PORT false CACHE BOOL "APEX queuing-port transport" FORCE)
elseif(LDP_LOCAL_TRANSPORT STREQUAL "UDP")
	set(CMAKE_USE_DDS_PROTO false CACHE BOOL "DDS protocol" FORCE)
	set(CMAKE_USE_UDP_PROTO true CACHE BOOL "UDP protocol" FORCE)
	set(CMAKE_USE_APEX_PORT false CACHE BOOL "APEX queuing-port transport" FORCE)
elseif(LDP_LOCAL_TRANSPORT STREQUAL "APEX")
	set(CMAKE_USE_DDS_PROTO false CACHE BOOL "DDS protocol" FORCE)
	set(CMAKE_USE_UDP_PROTO false CACHE BOOL "UDP protocol" FORCE)
	set(CMAKE_USE_APEX_PORT true CACHE BOOL "APEX queuing-port transport" FORCE)
elseif(LDP_LOCAL_TRANSPORT STREQUAL "TCP")
	set(CMAKE_USE_DDS_PROTO false CACHE BOOL "DDS protocol" FORCE)
	set(CMAKE_USE_UDP_PROTO false CACHE BOOL "UDP protocol" FORCE)
	set(CMAKE_USE_APEX_PORT false CACHE BOOL "APEX queuing-port transport" FORCE)
else()
	message(FATAL_ERROR "Unsupported LDP_LOCAL_TRANSPORT='${LDP_LOCAL_TRANSPORT}'. Use TCP, UDP, DDS or APEX.")
endif()
